version: 2
jobs:
    test:
        macos:
            Go: 1.13
            xcode: 11.6.0
        steps:
            - checkout
            - run:
                # The tests can be run locally without root, but there is a one-time prompt. We use
                # sudo on the CI machine to skip the prompt.
                name: Test
                command: sudo -E make test

workflows:
    version: 2
    test-workflow:
        jobs:
        - test